name: change_theme_er
description: "A high-performance, clean-code theme changer package using Hive, GetIt, and Bloc."
version: 0.0.3
homepage: https://github.com/Developeryilmaz/change_theme_er
issue_tracker: https://github.com/Developeryilmaz/change_theme_er/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15


platforms:
  android:
  ios:

license: MIT